name: fg_by_zodyy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  google_sign_in: ^5.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # Version compatible avec flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.0

flutter_launcher_icons:
  android: "launcher_icon"  # Generate launcher icons for Android
  ios: true  # Generate launcher icons for iOS
  remove_alpha_ios: true  # Remove alpha channel for iOS, required by Apple
  image_path: "assets/images/logo.png"  # Path to the base image
  min_sdk_android: 24  # Minimum Android SDK version
  adaptive_icon_background: "#ffffff"  # Background color for adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png"  # Foreground image for adaptive icons

flutter_native_splash:
  color: "#ffffff"  # Background color for the splash screen
  image: "assets/images/logoSplash.png"  # Image to display
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/  # Include all files in this folder
  # l10n:
  #   arb-dir: lib/l10n/
  #   template-arb-file: app_en.arb
  #   output-localization-file: app_localizations.dart
  #   output-class: AppLocalizations
