name: focus_goals_by_zodyy
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Add the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Plugins for launcher icons and splash screen
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.0.15

# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuration for launcher icons
flutter_launcher_icons:
  android: "launcher_icon"  # Generate launcher icons for Android
  ios: true  # Generate launcher icons for iOS
  remove_alpha_ios: true  # Remove alpha channel for iOS, required by Apple
  image_path: "assets/images/logo.png"  # Path to the base image
  min_sdk_android: 24  # Minimum Android SDK version
  adaptive_icon_background: "#ffffff"  # Background color for adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png"  # Foreground image for adaptive icons

# Configuration for splash screen
flutter_native_splash:
  color: "#ffffff"  # Background color for the splash screen
  image: "assets/images/logoSplash.png"  # Image to display
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Include all files in this folder
