// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCt7c1e3jowZvnWuQFfT5C1b9m1PFjTuo',
    appId: '1:758215266306:web:5d3d153c099e2d7724971b',
    messagingSenderId: '758215266306',
    projectId: 'focus-goals-by-zodyy',
    authDomain: 'focus-goals-by-zodyy.firebaseapp.com',
    storageBucket: 'focus-goals-by-zodyy.firebasestorage.app',
    measurementId: 'G-8BTGLH9ZZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANGFCJUS4Hnz0LSNMASMuG03rBaNc_YNs',
    appId: '1:758215266306:android:8db876535f78c7db24971b',
    messagingSenderId: '758215266306',
    projectId: 'focus-goals-by-zodyy',
    storageBucket: 'focus-goals-by-zodyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7PN4cSvkT7t6Mr7tADg0z2eBJNEH6d8',
    appId: '1:758215266306:ios:7083293357127f2124971b',
    messagingSenderId: '758215266306',
    projectId: 'focus-goals-by-zodyy',
    storageBucket: 'focus-goals-by-zodyy.firebasestorage.app',
    iosBundleId: 'com.example.fgByZodyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7PN4cSvkT7t6Mr7tADg0z2eBJNEH6d8',
    appId: '1:758215266306:ios:7083293357127f2124971b',
    messagingSenderId: '758215266306',
    projectId: 'focus-goals-by-zodyy',
    storageBucket: 'focus-goals-by-zodyy.firebasestorage.app',
    iosBundleId: 'com.example.fgByZodyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCt7c1e3jowZvnWuQFfT5C1b9m1PFjTuo',
    appId: '1:758215266306:web:2811978ecf7efbfc24971b',
    messagingSenderId: '758215266306',
    projectId: 'focus-goals-by-zodyy',
    authDomain: 'focus-goals-by-zodyy.firebaseapp.com',
    storageBucket: 'focus-goals-by-zodyy.firebasestorage.app',
    measurementId: 'G-TTJEEJLMYH',
  );
}
